apiVersion: v1
kind: Namespace
metadata:
  name: lil-kube

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: lil-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: kanelush/updimg3s
        ports:
        - containerPort: 3000
