apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-dj
  namespace: lil-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-dj
  template:
    metadata:
      labels:
        app: my-app-dj
    spec:
      containers:
      - name: my-app-dj
        image: kanelush/djapi
        ports:
        - containerPort: 8000
